# Generated by Django 6.0.5 on 2026-05-14 03:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity_of_pages', models.IntegerField()),
                ('isbn', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
